Display address
Agilefreaks/FreaksCatalog-Blockchain-UI pull request #2
Opened 2021-08-12 08:14 UTC by iooeduard

2021-08-12 11:29 UTC, luism-s requested changes

2021-08-12 11:29 UTC, dasilvaluis commented on packages/react-app/src/components/WalletButton/wallet-button.jsx
> +  function ButtonClick() {
The naming convention is something like `handleLoginButtonClick` or similar

2021-08-12 11:29 UTC, dasilvaluis commented on packages/react-app/src/components/Address/address.jsx
> +      <span>
There should be one more indentation here
```
{ provider && (
      <span>
```

2021-08-12 11:29 UTC, dasilvaluis commented on .gitignore
> +.editorconfig
Usually the editorconfig is tracked by git, so that every team member has the same config for indentation

2021-08-12 11:29 UTC, dasilvaluis commented on packages/react-app/src/components/Address/address.jsx
> +        Your Address is :&nbsp;
This works and is OK

This is another  popular option
```js
{ `Your Address is ${ address }` }
```

2021-08-12 11:29 UTC, dasilvaluis commented on packages/react-app/src/index.css
> +    'Segoe UI',
Maybe you don't need so many fonts, 'Helvetica' 'Arial'  sans-serif should be enough

2021-08-12 11:29 UTC, luism-s commented on packages/react-app/src/services/web3-service.js
> +export default { getAddress };
By convention there should be an empty line between these expressions

2021-08-13 08:15 UTC, iooeduard commented on packages/react-app/src/components/Address/address.jsx
> +      <span>
My linter said that it's ok this way. Might be a lint config issue?

2021-08-13 08:19 UTC, iooeduard commented on packages/react-app/src/components/Address/address.jsx
> +        Your Address is :&nbsp;
Forgot about the other option, thanks!

2021-08-16 09:34 UTC, levelboy commented on packages/react-app/package.json
> +    "web3": "^1.5.1",
Lateley, ethers.js is used in favor of web3.js. Any reason why we chose web3?

2021-08-16 10:40 UTC, iooeduard commented on packages/react-app/package.json
> +    "web3": "^1.5.1",
Not really, I used it mainly cause it was mentioned and showcased in the cryptozombies tutorial. Will change to ethers.js since it's better.

2021-08-16 11:07 UTC, luism-s approved these changes

2021-08-16 11:09 UTC, merged

2021-08-31 06:12 UTC, iooeduard commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display wallet address](https://trello.com/c/Q5hg5m9c/193-display-wallet-address)