List freaks
Agilefreaks/FreaksCatalog-Blockchain-UI pull request #4
Opened 2021-08-18 11:29 UTC by iooeduard

2021-08-18 12:04 UTC, luism-s requested changes

2021-08-18 12:04 UTC, dasilvaluis commented on packages/react-app/src/components/AmountShared/amount-shared.jsx
> +  return (
Add a line breack between the function and the return statement

2021-08-18 12:04 UTC, dasilvaluis commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +    function parseFreaks({ _name, _scor }) {
Consider moving this function to a helpers file, so that it can be used across the application

2021-08-18 12:04 UTC, dasilvaluis commented on packages/react-app/src/freaks.css
> +#textbox {
IDs shouldt be used as css selectors

2021-08-18 12:04 UTC, dasilvaluis commented on packages/react-app/src/services/ethers-contract.js
> +  const deployedAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';
These strings should be received as arguments
Ultimately they will be environment constants

2021-08-18 12:04 UTC, luism-s commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +    return (
Add line break between statements

2021-08-18 12:04 UTC, luism-s commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +  function renderFreaks(freak, index) {
It is a single freak, so:

```suggestion
  function renderFreak(freak, index) {
```

2021-08-18 12:04 UTC, luism-s commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +        <td>{ share / 10 }</td>
Do not use magic numbers.
Instead create a const for each with a meaningful name

I should add a linter rule for this..

2021-08-18 12:04 UTC, luism-s commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +    if (contract !== null) {
Thinking back, you can directly evaluate the constant.
It is better because if you change the initial value to `undefined`, you wont need to change this condition.

```suggestion
    if (contract) {
```

2021-08-18 12:04 UTC, luism-s commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +import PropTypes from 'prop-types';
External libraries should come before local files

2021-08-18 15:45 UTC, alexandru-calinoiu commented on packages/react-app/src/components/AmountShared/amount-shared.jsx
> +  return (
Can we have this in a linter?

2021-08-18 15:46 UTC, alexandru-calinoiu commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +import PropTypes from 'prop-types';
There should be a library out there that enforces styles.

2021-08-18 16:03 UTC, iooeduard commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +import PropTypes from 'prop-types';
> There should be a library out there that enforces styles.

I will remove the .css since we will be using the rimble-ui. Thanks

2021-08-23 10:17 UTC, luism-s approved these changes

2021-08-23 10:17 UTC, merged

2021-08-31 06:13 UTC, iooeduard commented
![](https://github.trello.services/images/mini-trello-icon.png) [List Freaks](https://trello.com/c/NyVgriP7/194-list-freaks)