Implement rimble UI
Agilefreaks/FreaksCatalog-Blockchain-UI pull request #5
Opened 2021-08-23 08:29 UTC by iooeduard

![image](https://user-images.githubusercontent.com/72457552/130415827-96c718e9-98f2-44b3-a86e-1da949efebe7.png)

2021-08-23 08:49 UTC, luism-s requested changes

2021-08-23 08:49 UTC, luism-s commented on packages/react-app/src/services/ethers-contract.js
> +  const deployedAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';
Can we start extracting these values?
Which are user/session dependent and which are environment?

The environment should be loaded using a .env file, as shown here:
https://tacomanator.medium.com/environments-with-create-react-app-7b645312c09d

User and session values should be received through function arguments.

2021-08-23 08:49 UTC, luism-s commented on packages/react-app/src/helpers/contract-parser.js
> +export function parseFreaks({ _name, _scor }) {
Consider renaming the `_scor` on the smart contract, it seems to be a typo

2021-08-23 08:49 UTC, luism-s commented on packages/react-app/src/components/FreaksList/freaks-list.jsx
> +          { sharePercentage }
Maybe it is easier as

```suggestion
          { `${ sharePercentage } %` }
```

2021-08-23 10:14 UTC, luism-s approved these changes

2021-08-23 10:17 UTC, luism-s requested changes
Re-requesting changes

2021-08-24 07:05 UTC, luism-s requested changes

2021-08-24 07:05 UTC, luism-s commented on packages/react-app/src/services/ethers-contract.js
> +  const localhost = 'http://localhost:8545';
```suggestion
  const providerAddress = 'http://localhost:8545';
```

2021-08-24 07:05 UTC, luism-s commented on packages/react-app/src/services/ethers-contract.js
> +  const deployedAddress = process.env.REACT_APP_CONTRACT_ADDRESS;
packages/react-app/src/config.js

const CONTRACT_ADDRESS = process.env.REACT_APP_CONTRACT_ADDRESS;

export default {
  CONTRACT_ADDRESS
};

2021-08-24 07:05 UTC, luism-s commented on packages/react-app/src/hooks/useEthersContract.js
> +    getContract().then(setContract);
async function ...() {
const contract = await getContract()

setContract(contract);
}

2021-08-24 08:28 UTC, luism-s approved these changes

2021-08-24 08:29 UTC, merged

2021-08-31 06:13 UTC, iooeduard commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implemet rimble-ui](https://trello.com/c/KHkWhy6i/195-implemet-rimble-ui)