Pie colors and table height fix
Agilefreaks/FreaksCatalog-Blockchain-UI pull request #6
Opened 2021-08-30 07:35 UTC by iooeduard

2021-08-30 09:02 UTC, luism-s requested changes

2021-08-30 09:02 UTC, dasilvaluis commented on packages/react-app/src/components/ProfitPie/profit-pie.jsx
> +    datasets:
The standard in JS is to not have a line break between the key and the value

So this

```
datasets: [
```
instead of 
```
datasets:
[
```

One more rule to the linter..

2021-08-30 09:02 UTC, dasilvaluis commented on packages/react-app/src/components/ProfitPie/profit-pie.jsx
> +    }
You an do this with a map.

```js
function generateRandomColor() {
      const r = Math.floor(Math.random() * 255);
      const g = Math.floor(Math.random() * 255);
      const b = Math.floor(Math.random() * 255);
      return `rgb(${ r }, ${ g }, ${ b })`;
}

return labels.map(generateRandomColor)
```

On the side note, it would be interesting to have a fixed color for every person, based on their ID

2021-08-30 09:02 UTC, luism-s commented on package.json
> +    "chartjs": "^0.3.24"
This shouldnt be here.
Do `yarn remove chartjs` on the root, to make sure it is removed from the yarn.lock.

2021-08-30 09:02 UTC, luism-s commented on packages/react-app/src/components/ProfitPie/profit-pie.jsx
> +  function dynamicColors() {
95% (made up percentage) of the cases functions should start with a verb

```suggestion
  function getDynamicColors() {
```

2021-08-31 06:12 UTC, iooeduard commented
![](https://github.trello.services/images/mini-trello-icon.png) [Profit pie](https://trello.com/c/AJi2ua8J/197-profit-pie)

2021-08-31 07:08 UTC, luism-s approved these changes

2021-08-31 07:09 UTC, merged