Add component for each Role and withdraw text.
Agilefreaks/FreaksCatalog-Blockchain-UI pull request #7
Opened 2021-08-31 07:23 UTC by iooeduard

2021-08-31 07:46 UTC, luism-s requested changes

2021-08-31 07:46 UTC, luism-s commented on packages/react-app/src/components/WithdrawText/withdraw-text.jsx
> +          Hi, Freak you can withdraw up to: XXXX USDC
Maybe you can already define a prop for the value he can withdraw?

2021-08-31 07:46 UTC, luism-s commented on packages/react-app/src/components/WithdrawText/withdraw-text.jsx
> +      <Flex>
In this case you can wrap everything in a 

```js
<Flex flexDirection="column">
  <Text>...</Text>
  <Flex>
    <Text>...</Text>
    <Field>...</Field>
  </Flex>
</Flex>
```

2021-08-31 07:46 UTC, luism-s commented on packages/react-app/src/components/WithdrawText/withdraw-text.jsx
> +function WithdrawText() {
Would it make more sense to call it `WithdrawForm`?

2021-08-31 07:50 UTC, iooeduard commented on packages/react-app/src/components/WithdrawText/withdraw-text.jsx
> +          Hi, Freak you can withdraw up to: XXXX USDC
Yes, good idea.

2021-08-31 08:10 UTC, iooeduard commented on packages/react-app/src/components/WithdrawText/withdraw-text.jsx
> +function WithdrawText() {
Probably yes, thanks.

2021-08-31 08:34 UTC, luism-s approved these changes

2021-08-31 08:35 UTC, merged

2021-09-02 11:10 UTC, iooeduard commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI component for non-freak callers](https://trello.com/c/W1wkEIuM/206-ui-component-for-non-freak-callers)