Adapt UI based on the person accesing the page.
Agilefreaks/FreaksCatalog-Blockchain-UI pull request #8
Opened 2021-09-01 07:44 UTC by iooeduard

'isFinancial' and 'isFreak' functions are yet to be implemented on the smart contract side.

2021-09-01 13:34 UTC, luism-s requested changes

2021-09-01 13:34 UTC, luism-s commented on packages/react-app/src/components/Roles/roles.jsx
> +  return (
I realized that we could have done something like, but I over-engineered a little bit :)
Up to you if you prefer this approach.

```js
const rolesPages = [
  {
    matcher: contract.isFinancial,
    getPage: () => <FinancialRole />
  },
  {
    matcher: contract.isFreak,
    getPage: () => <FreakRole />
  },
  {
    matcher: (address) => !contract.isFreak(address) && !contract.isFinancial(address),
    getPage: () => <FreakRole />
  }
];

const page = rolesPages.find(({ matcher }) => matcher(address))?.getPage();

return page
```

It this latest you would need neither the RoleRouter or the RoleRoute components

2021-09-01 13:34 UTC, luism-s commented on packages/react-app/src/App.jsx
> +          <RoleComponents />
I suggest something more meaningful

```suggestion
          <RolePageSwitcher />
```

2021-09-01 13:49 UTC, iooeduard commented on packages/react-app/src/components/Roles/roles.jsx
> +  return (
Looks super clean but I like the other approach more since I fully understood it.

2021-09-02 08:41 UTC, dasilvaluis approved these changes

2021-09-02 08:42 UTC, merged

2021-09-02 11:08 UTC, iooeduard commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI should adapt to the role of the caller](https://trello.com/c/Ecvwex6K/205-ui-should-adapt-to-the-role-of-the-caller)